name: macOS CI

on:
  push

jobs:
  build:
    name: build
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
             cd projectfiles/xcode
             xcodebuild -target Emulator -configuration Debug
